name: CI for code

on:
  push:
    tags: ['*']
    branches:
    - 'main'
    - 'feature/*'
    - 'fix/*'
    - 'refactor/*'

jobs:
  # Lint all JS code by Deno
  js-denolint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Lint all js/ts files
      run: deno lint


  # Run all JS unit-tests by deno test
  js-denotest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/tests/js_denotest

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Run all tests
      run: deno test --parallel --coverage Test_*.js Test_*.ts */Test_*.js  # Quick fix for sub directory test code
    - name: Report coverage as actions summary
      env:
        NO_COLOR: "true"  # Disable deno color output
      run: |
        echo '## Deno coverage report' >> $GITHUB_STEP_SUMMARY
        echo >> $GITHUB_STEP_SUMMARY  # Print blank newline
        deno coverage | grep -E -v '^-+$' | sed -e 's/^/|/g' | sed '2i|---|---|---|' >> $GITHUB_STEP_SUMMARY
        #               remove '---...' line
        #                                   add '|' to line head
        #                                                      complete markdown table syntax
