name: Run all JS unittests by deno test

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'
      - 'refactor/*'

jobs:
  js-denotest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/tests/js_denotest

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    # - name: Run all tests
      # Temporary disabled for construction of test code
      # run: deno test --parallel **Test_*.js
