name: Run all JS unittests by vitest

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'
      - 'refactor/*'

jobs:
  js-vitest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/tests/js_vitest

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Set up Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Dependency restore
      id: dependency-restore
      uses: actions/cache@v4
      with:
        key: js-vitest-depend-${{ runner.os }}-${{ hashFiles('src/tests/js_vitest/package-lock.json') }}
        path: src/tests/js_vitest/node_modules
    - name: Install node dependencies
      if: steps.dependency-restore.outputs.cache-hit != 'true'
      run: npm ci
    - name: Run all tests
      run: npm test
