name: Run all python unittests

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'
      - 'refactor/*'

jobs:
  python-unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/tests/py_unittest

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip3 install numpy pydub
    - name: Run all tests
      run: |
        python3 -m unittest discover ./ "Test_*.py" -v
