name: Run all python unittests

on: [push]

jobs:
  python-unittest:
    runs-on: ubuntu-latest

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip3 install numpy pydub
    - name: Run all tests
      run: |
        python3 -m unittest discover src/tests/ "Test_*.py" -v
